const TYPES = {
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_ALL_FROM_CART: "DELETE_ALL_FROM_CART",
    DELETE_PRODUCT_FROM_CART: "DELETE_PRODUCT_FROM_CART",
    CALCULATE_TOTAL_PRICE_OF_THE_CART: "CALCULATE_TOTAL_PRICE_OF_THE_CART",
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    SELECT_OPTION: "SELECT_OPTION",
    ADD_QUANTITY: "ADD_QUANTITY",
    REMOVE_QUANTITY: "REMOVE_QUANTITY",
    OPEN_MODAL_CARRO: "OPEN_MODAL_CARRO",
    CLOSE_MODAL_CARRO: "CLOSE_MODAL_CARRO",
  };
  
  export default TYPES;
  