name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - master # Asegúrate de que esta sea la rama en la que quieres desplegar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '>=18.14.1' # Usa una versión de Node.js compatible con tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist # Asegúrate de que este es el directorio de build

